### ISSUE TITLE
【ユーザー登録】パスワードが隠されていない

### ISSUE THREAD

**Issue by notch0314** [osakamiseri/GeekSNS_app#4]
# やること
パスワードが隠されていないので「●●●●●●●」のように隠す

# スクリーンショット
<img width="403" alt="スクリーンショット 2020-04-17 17 45 25" src="https://user-images.githubusercontent.com/17807114/79550486-5a520180-80d3-11ea-8fb9-d1d6e646451a.png">

**Comment by osakamiseri** [comment]
851beef9f4f1248a3ad69233b0f0acf19f62e610
修正しました！
